AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Performs a periodic check of the given site, erroring out on test failure.'
Resources:
  notificationservice:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: >-
        Performs a periodic check of the given site, erroring out on test
        failure.
      MemorySize: 128
      Timeout: 10
      Role: >-
        arn:aws:iam::001160264744:role/service-role/notification_service-role-rnhmakas
      Tags:
        'lambda-console:blueprint': lambda-canary
      RuntimePolicy:
        UpdateRuntimeOn: Auto
